# What standard to use. This is optional and defaults to VHDL2008.
standard = "2008"
# File names are either absolute or relative to the parent folder of the vhdl_ls.toml file
[libraries]
micro.files = [
    'src/*.vhd',
]

#std.files = [
#    '/usr/lib/ghdl/src/std/*.vhdl',
#    '/usr/lib/ghdl/src/std/v08/*.vhdl',
#]
#
#ieee.files = [
#    '/usr/lib/ghdl/src/ieee2008/*.vhdl',
#    '/usr/lib/ghdl/src/ieee/*.vhdl',
#]

# Libraries can be marked as third-party to disable some analysis warnings, such as unused declarations
[lint]
unused = 'error' # Upgrade the 'unused' diagnostic to the 'error' severity
unnecessary_work_library = false # Disable linting for the 'library work;' statement
